name: Terraform Azure GitHub Action

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Import
        run: |
          terraform import azurerm_resource_group.example /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform

          terraform import azurerm_virtual_network.example /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Network/virtualNetworks/vnet-terraform

          terraform import azurerm_subnet.example /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Network/virtualNetworks/vnet-terraform/subnets/subnet-terraform

          terraform import azurerm_network_interface.example[0] /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Network/networkInterfaces/terraform-nic-0
          terraform import azurerm_network_interface.example[1] /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Network/networkInterfaces/terraform-nic-1

          terraform import azurerm_public_ip.example[0] /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Network/publicIPAddresses/terraform-public-ip-0
          terraform import azurerm_public_ip.example[1] /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Network/publicIPAddresses/terraform-public-ip-1

          terraform import azurerm_storage_account.example /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Storage/storageAccounts/terraformstgacc25

          terraform import azurerm_storage_container.example /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Storage/storageAccounts/terraformstgacc25/blobServices/default/containers/terraformstgcont

          terraform import azurerm_virtual_machine.example[0] /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Compute/virtualMachines/terraform-vm-0
          terraform import azurerm_virtual_machine.example[1] /subscriptions/76ee20cb-86ed-48e1-a2a8-abc9d6ed9969/resourceGroups/rg-terraform/providers/Microsoft.Compute/virtualMachines/terraform-vm-1

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
